#!/usr/bin/env bash
set -e

CONDA_ROOT=${CONDA_ROOT:-/opt/conda}
CONDA_ENV_NAME=${CONDA_ENV_NAME:-chipyard}
CONDA_ENV_PREFIX=${CONDA_ENV_PREFIX:-${CONDA_ROOT}/envs/${CONDA_ENV_NAME}}
CHIPYARD_DIST=${CHIPYARD_DIST:-/opt/chipyard-dist}
PREFERRED_WORKDIR=${PREFERRED_WORKDIR:-/work/chipyard}

source "${CONDA_ROOT}/etc/profile.d/conda.sh"
if [ -d "${CONDA_ENV_PREFIX}" ]; then
    conda activate "${CONDA_ENV_PREFIX}"
else
    conda activate "${CONDA_ENV_NAME}"
fi

export RISCV="${CONDA_PREFIX}/riscv-tools"
export PATH="${RISCV}/bin:${PATH}"

if [ -f "${PREFERRED_WORKDIR}/build-setup.sh" ] || [ -d "${PREFERRED_WORKDIR}/.git" ]; then
    export CHIPYARD_WORKDIR="${PREFERRED_WORKDIR}"
else
    export CHIPYARD_WORKDIR="${CHIPYARD_DIST}"
fi

export CY_DIR="${CHIPYARD_WORKDIR}"

if [ -d "${CHIPYARD_WORKDIR}/software/firemarshal" ]; then
    export PATH="${CHIPYARD_WORKDIR}/software/firemarshal:${PATH}"
fi

refresh_env_sh() {
    local target_dir="$1"
    local target_env="${target_dir}/env.sh"
    local tmp_env

    if [ ! -d "${target_dir}" ] || [ ! -w "${target_dir}" ]; then
        return 0
    fi

    tmp_env=$(mktemp)
    cat > "${tmp_env}" <<EOF
# line auto-generated by chipyard Docker entrypoint
export CY_DIR="${target_dir}"
export CHIPYARD_WORKDIR="${target_dir}"

if [ -f "${CONDA_ROOT}/etc/profile.d/conda.sh" ]; then
    source "${CONDA_ROOT}/etc/profile.d/conda.sh"
else
    echo "::ERROR:: ${CONDA_ROOT}/etc/profile.d/conda.sh not found"
    return 1
fi

conda activate "${CONDA_ENV_PREFIX}"
export RISCV="\${CONDA_PREFIX}/riscv-tools"
export PATH="\${RISCV}/bin:\${PATH}"

if [ -f "${target_dir}/scripts/fix-open-files.sh" ]; then
    source "${target_dir}/scripts/fix-open-files.sh"
fi

if [ -d "${target_dir}/software/firemarshal" ]; then
    export PATH="${target_dir}/software/firemarshal:\${PATH}"
fi
EOF

    if [ -f "${target_env}" ] && cmp -s "${tmp_env}" "${target_env}"; then
        rm -f "${tmp_env}"
        return 0
    fi

    if [ -f "${target_env}" ]; then
        cp "${target_env}" "${target_env}.host-backup.$(date +%Y%m%d%H%M%S)"
    fi

    mv "${tmp_env}" "${target_env}"
}

if [ "${CHIPYARD_WORKDIR}" != "${CHIPYARD_DIST}" ]; then
    refresh_env_sh "${CHIPYARD_WORKDIR}"
fi

if [ "$#" -eq 0 ]; then
    set -- /bin/bash
fi

exec "$@"
